name: Code Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    paths:
      - "pydglab_ws/**"
      - "tests/**"
      - "pyproject.toml"
  pull_request:
    paths:
      - "pydglab_ws/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  test:
    name: Test With Coverage
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
          poetry run pytest -v --capture=sys --cov --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: ${{ matrix.os }}-${{ matrix.python-version }}
